substitutions:
  _REGION: asia-east1
  _REPO: vibe-fit

  _BACKEND_SERVICE: vibe-fit-backend-dev
  _WORKER_SERVICE: vibe-fit-worker-dev

  _BACKEND_SERVICE_ACCOUNT: vibe-fit-backend-sa
  _WORKER_SERVICE_ACCOUNT: vibe-fit-worker-sa

  _INSTANCE_ID: vibe-fit-postgres
  _FRONTEND_URL: https://vibe-fit-frontend-1085526549756.asia-east1.run.app
  _GOOGLE_CLIENT_ID: 1085526549756-tq6v0pr6n71n9nfthqpah8fvgc9j0aar.apps.googleusercontent.com
  _PUBSUB_TOPIC_BACKUP_CREATED: vibe-fit-backup-created

steps:
  - id: backend-typecheck
    name: node:20-alpine
    dir: backend
    entrypoint: sh
    args:
      - -c
      - |
        npm ci
        npm run typecheck

  - id: backend-build-ts
    name: node:20-alpine
    dir: backend
    entrypoint: sh
    args:
      - -c
      - |
        npm ci
        npm run build

  - id: build-backend-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_BACKEND_SERVICE}:${BUILD_ID}
      - backend

  - id: push-backend-image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_BACKEND_SERVICE}:${BUILD_ID}

  - id: deploy-backend-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_BACKEND_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_BACKEND_SERVICE}:${BUILD_ID}
      - --region=${_REGION}
      - --project=${PROJECT_ID}
      - --allow-unauthenticated
      - --port=8080
      - --service-account=${_BACKEND_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
      - --add-cloudsql-instances=${PROJECT_ID}:${_REGION}:${_INSTANCE_ID}
      - --set-env-vars=NODE_ENV=production,AUTH_MODE=google,DATA_MODE=postgres,LOG_PRETTY=false,CORS_ORIGIN=${_FRONTEND_URL},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},EVENT_PUBLISHER=pubsub,PUBSUB_TOPIC_BACKUP_CREATED=${_PUBSUB_TOPIC_BACKUP_CREATED}
      - --set-secrets=DATABASE_URL=vibe-fit-database-url:latest,JWT_SECRET=vibe-fit-jwt-secret:latest

  - id: deploy-worker
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_WORKER_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_BACKEND_SERVICE}:${BUILD_ID}
      - --region=${_REGION}
      - --project=${PROJECT_ID}
      - --no-allow-unauthenticated
      - --port=8080
      - --service-account=${_WORKER_SERVICE_ACCOUNT}@${PROJECT_ID}.iam.gserviceaccount.com
      - --command=node
      - --args=dist/worker.js
      - --set-env-vars=NODE_ENV=production,AUTH_MODE=mock,DATA_MODE=mock,LOG_PRETTY=false,EVENT_PUBLISHER=mock
      - --set-secrets=JWT_SECRET=vibe-fit-jwt-secret:latest

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_BACKEND_SERVICE}:${BUILD_ID}